### PR TITLE
Update interpreter directive in python scripts

### PR DESCRIPTION
**Pull request by gbp**
Change to `/usr/bin/env` so we load the Python version from the current
environment.

And use `python2` as these script are old and will error when using
Python 3.

See: https://github.com/mysociety/alaveteli/issues/5841

### CODE REVIEW

**Comment by gbp** [comment]
@dracos can you seen any issues with this? We need this for https://github.com/mysociety/alaveteli/pull/6038

**Review by dracos — APPROVED** [review]
Fine by me, I'll take a look at making it python2/3 agnostic, shouldn't be tricky and I've had to do that elsewhere recently.

**Comment by dracos** [comment]
Have pushed a commit that hopefully makes it python 2/3 agnostic, plus switch to safe_load to remove the yaml.load warning.

**Comment by gbp** [comment]
> Have pushed a commit that hopefully makes it python 2/3 agnostic, plus switch to safe_load to remove the yaml.load warning.

Nice, thanks for doing this. Looks like this is compatible with the latest PyYAML too :tada:

**Pull request merged**
